"""YAML parser for WireViz Studio core."""

from pathlib import Path
from typing import Any, Dict, List, Optional

from wireviz_studio import APP_NAME
from wireviz_studio.core.exceptions import ValidationError, YAMLParseError
from wireviz_studio.core.harness import Harness
from wireviz_studio.core.helpers import (
    expand,
    get_single_key_and_value,
    is_arrow,
    smart_file_resolve,
)
from wireviz_studio.core.models import Metadata, Options, Tweak


def parse_yaml(data: Dict[str, Any], image_paths: Optional[List[Path]] = None) -> Harness:
    """Parse a YAML dictionary into a Harness object without file I/O."""
    if not isinstance(data, dict):
        raise YAMLParseError(f"Expected dict YAML payload, got {type(data)}")

    try:
        return _parse_data(data, image_paths=list(image_paths or []))
    except (YAMLParseError, ValidationError):
        raise
    except Exception as exc:
        raise ValidationError(str(exc)) from exc


def _parse_data(yaml_data: Dict[str, Any], image_paths: List[Path]) -> Harness:
    template_connectors = {}
    template_cables = {}

    harness = Harness(
        metadata=Metadata(**yaml_data.get("metadata", {})),
        options=Options(**yaml_data.get("options", {})),
        tweak=Tweak(**yaml_data.get("tweak", {})),
    )
    designators_and_templates = {}
    autogenerated_designators = {}

    if "title" not in harness.metadata:
        harness.metadata["title"] = f"{APP_NAME} diagram and BOM"

    sections = ["connectors", "cables", "connections"]
    types = [dict, dict, list]
    for section_name, expected_type in zip(sections, types):
        if section_name in yaml_data and type(yaml_data[section_name]) == expected_type:
            if len(yaml_data[section_name]) > 0 and expected_type == dict:
                for key, attributes in yaml_data[section_name].items():
                    image = attributes.get("image")
                    if isinstance(image, dict):
                        image_path = image["src"]
                        if image_path and not Path(image_path).is_absolute():
                            image["src"] = smart_file_resolve(image_path, image_paths)
                    if section_name == "connectors":
                        template_connectors[key] = attributes
                    elif section_name == "cables":
                        template_cables[key] = attributes
        else:
            yaml_data[section_name] = {} if expected_type == dict else []

    connection_sets = yaml_data["connections"]
    template_separator_char = harness.options.template_separator

    def resolve_designator(value: str, separator: str):
        if separator in value:
            if value.count(separator) > 1:
                raise ValidationError(
                    f"{value} - Found more than one separator ({separator})"
                )
            template, designator = value.split(separator)
            if designator == "":
                autogenerated_designators[template] = (
                    autogenerated_designators.get(template, 0) + 1
                )
                designator = f"__{template}_{autogenerated_designators[template]}"
            if designator in designators_and_templates:
                if designators_and_templates[designator] != template:
                    raise ValidationError(
                        f"Trying to redefine {designator} from {designators_and_templates[designator]} to {template}"
                    )
            else:
                designators_and_templates[designator] = template
        else:
            template, designator = (value, value)
            if designator not in designators_and_templates:
                designators_and_templates[designator] = template
        return template, designator

    alternating_types = ["connector", "cable/arrow"]
    expected_type = None

    def check_type(designator: str, template: str, actual_type: str):
        nonlocal expected_type
        if not expected_type:
            expected_type = actual_type
        if actual_type != expected_type:
            raise ValidationError(
                f'Expected {expected_type}, but "{designator}" ("{template}") is {actual_type}'
            )

    def alternate_type():
        nonlocal expected_type
        expected_type = alternating_types[1 - alternating_types.index(expected_type)]

    for connection_set in connection_sets:
        connectioncount = []
        for entry in connection_set:
            if isinstance(entry, list):
                connectioncount.append(len(entry))
            elif isinstance(entry, dict):
                connectioncount.append(len(expand(list(entry.values())[0])))
        if not any(connectioncount):
            connectioncount = [1]
        if len(set(connectioncount)) > 1:
            raise ValidationError(
                "All items in connection set must reference the same number of connections"
            )
        connectioncount = connectioncount[0]

        for index, entry in enumerate(connection_set):
            if isinstance(entry, str):
                connection_set[index] = [entry] * connectioncount

        for index, entry in enumerate(connection_set):
            if isinstance(entry, list):
                for subindex, item in enumerate(entry):
                    _, designator = resolve_designator(item, template_separator_char)
                    connection_set[index][subindex] = designator
            elif isinstance(entry, dict):
                key = list(entry.keys())[0]
                _, designator = resolve_designator(key, template_separator_char)
                connection_set[index] = {designator: entry[key]}

        for index, entry in enumerate(connection_set):
            if isinstance(entry, list):
                connection_set[index] = [{designator: 1} for designator in entry]
            elif isinstance(entry, dict):
                designator = list(entry.keys())[0]
                pinlist = expand(entry[designator])
                connection_set[index] = [{designator: pin} for pin in pinlist]

        expected_type = None
        for entry in connection_set:
            for item in entry:
                designator = list(item.keys())[0]
                template = designators_and_templates[designator]

                if designator in harness.connectors:
                    check_type(designator, template, "connector")
                elif template in template_connectors:
                    check_type(designator, template, "connector")
                    harness.add_connector(name=designator, **template_connectors[template])
                elif designator in harness.cables:
                    check_type(designator, template, "cable/arrow")
                elif template in template_cables:
                    check_type(designator, template, "cable/arrow")
                    harness.add_cable(name=designator, **template_cables[template])
                elif is_arrow(designator):
                    check_type(designator, template, "cable/arrow")
                else:
                    raise ValidationError(
                        f"{template} is an unknown template/designator/arrow."
                    )
            alternate_type()

        connection_set = list(map(list, zip(*connection_set)))

        for index_entry, entry in enumerate(connection_set):
            for index_item, item in enumerate(entry):
                designator = list(item.keys())[0]

                if designator in harness.cables:
                    if index_item == 0:
                        from_name, from_pin = (None, None)
                    else:
                        from_name, from_pin = get_single_key_and_value(entry[index_item - 1])
                    via_name, via_pin = (designator, item[designator])
                    if index_item == len(entry) - 1:
                        to_name, to_pin = (None, None)
                    else:
                        to_name, to_pin = get_single_key_and_value(entry[index_item + 1])
                    harness.connect(from_name, from_pin, via_name, via_pin, to_name, to_pin)
                elif is_arrow(designator):
                    if index_item == 0:
                        raise ValidationError("An arrow cannot be at the start of a connection set")
                    if index_item == len(entry) - 1:
                        raise ValidationError("An arrow cannot be at the end of a connection set")

                    from_name, from_pin = get_single_key_and_value(entry[index_item - 1])
                    to_name, to_pin = get_single_key_and_value(entry[index_item + 1])
                    if "-" in designator:
                        harness.add_mate_pin(from_name, from_pin, to_name, to_pin, designator)
                    elif "=" in designator and index_entry == 0:
                        harness.add_mate_component(from_name, to_name, designator)

    proposed_components = list(template_connectors.keys()) + list(template_cables.keys())
    used_components = set(designators_and_templates.values())
    forgotten_components = [component for component in proposed_components if component not in used_components]
    if forgotten_components:
        print("Warning: The following components are not referenced in any connection set:")
        print(", ".join(forgotten_components))

    if "additional_bom_items" in yaml_data:
        for line in yaml_data["additional_bom_items"]:
            harness.add_bom_item(line)

    return harness
